-- 007_asset_class_shell.sql — records Chip 2-shell: asset_class family taxonomy (2-level).
-- GENERATED by gen_shell_seed.py — do not hand-edit; change the taxonomy in the generator + regen.
-- Parents = NETA categories (27: 19 active + 8 future). Leaves = practical apparatus classes (36).
-- Idempotent: ON CONFLICT (class_code). Anchor: parent.neta_category in records.neta_procedures.category.
BEGIN;
SET client_encoding TO 'UTF8';

-- Parents (NETA categories) — inserted first to satisfy the self-FK from leaves.
INSERT INTO records.asset_classes (asset_class_id, class_code, name, neta_category, parent_class_id, is_active) VALUES
  ('ed418cb7-bfd9-564d-9bd0-987d7c320b5e', 'circuit_breakers', 'Circuit Breakers', 'circuit_breakers', NULL, true),
  ('10d077d6-b28a-5d2f-b192-5225ffe7c946', 'transformers', 'Transformers', 'transformers', NULL, true),
  ('c04a48f5-d000-536f-a2a3-2c38e09bed32', 'switchgear', 'Switchgear and Switchboard Assemblies', 'switchgear', NULL, true),
  ('f42e536f-14bd-5d40-8707-0ad0e7a906e3', 'instrument_transformers', 'Instrument Transformers', 'instrument_transformers', NULL, true),
  ('d1d4d633-a0fa-56de-8c56-0022a17d007e', 'cables', 'Cables', 'cables', NULL, true),
  ('aaddcd69-3813-506c-ba43-05e700b98dd7', 'busways', 'Metal-Enclosed Busways', 'busways', NULL, true),
  ('e525bbfa-91f1-527c-9d3e-7e28a2b030a7', 'capacitors_reactors_resistors', 'Capacitors, Reactors, and Resistors', 'capacitors_reactors_resistors', NULL, true),
  ('19251f8c-0141-54bb-bbee-3f455e997829', 'motor_control', 'Motor Control', 'motor_control', NULL, true),
  ('95250548-46d9-59e5-b698-c3208f562926', 'rotating_machinery', 'Rotating Machinery', 'rotating_machinery', NULL, true),
  ('4b655ad2-5102-5e1b-9ce5-6270f4ebac72', 'dc_systems', 'Direct-Current Systems', 'dc_systems', NULL, true),
  ('fc3dbb0d-1469-5794-9699-f128ed4aa9b7', 'emergency_systems', 'Emergency Systems', 'emergency_systems', NULL, true),
  ('b86e3489-727b-52cd-970f-932aa3f1dc73', 'switches', 'Switches', 'switches', NULL, true),
  ('c7225c25-d380-5330-850e-81ebc76c5be9', 'grounding_systems', 'Grounding Systems', 'grounding_systems', NULL, true),
  ('f61bd960-dc83-5348-af99-a4835aaf886d', 'surge_protection', 'Surge Protective Devices', 'surge_protection', NULL, true),
  ('47a6a810-65f0-555f-8396-96c5daecdf3e', 'regulating_apparatus', 'Regulating Apparatus', 'regulating_apparatus', NULL, true),
  ('5c44b02d-5f3d-5db2-83ae-92ddee75de57', 'circuit_switchers', 'Circuit Switchers', 'circuit_switchers', NULL, true),
  ('ff444803-fb28-526d-ad6d-a5605e330ea3', 'outdoor_bus', 'Outdoor Bus Structures', 'outdoor_bus', NULL, true),
  ('9f3caee7-3185-5030-acbf-38a8f72b5b0f', 'metering_devices', 'Metering Devices', 'metering_devices', NULL, true),
  ('279e0012-0285-5bdf-b3e2-6bcab1e06245', 'protective_relays', 'Protective Relays', 'protective_relays', NULL, true),
  ('ab81a50c-4dd5-57c0-9e60-3498a69da283', 'reclosers_sectionalizers', 'Automatic Circuit Reclosers and Line Sectionalizers', 'reclosers_sectionalizers', NULL, false),
  ('d1979a10-345c-56fb-abe8-84629b0ed4de', 'network_protectors', 'Network Protectors', 'network_protectors', NULL, false),
  ('a453c351-ec9f-5c04-a250-113ab3eb00d3', 'ground_fault_protection', 'Ground-Fault Protection Systems', 'ground_fault_protection', NULL, false),
  ('a03d93b9-8f16-5cbc-8684-9289bbe6aa9e', 'adjustable_speed_drives', 'Adjustable Speed Drive Systems', 'adjustable_speed_drives', NULL, false),
  ('42d6b38b-5a26-57aa-98cc-acb9b2fe5b1a', 'automation_communications', 'Automation Systems and Communications', 'automation_communications', NULL, false),
  ('da981113-1495-5d3d-a9de-c2681f9b4504', 'ev_charging', 'Electric Vehicle Charging Systems', 'ev_charging', NULL, false),
  ('c054d450-fcd5-59de-afc6-1f48b8b35d06', 'fiber_optic', 'Fiber-Optic Cables', 'fiber_optic', NULL, false),
  ('da157752-9641-59bc-96e6-0cff2c539380', 'renewable_energy', 'Renewable and Emerging Systems', 'renewable_energy', NULL, false)
ON CONFLICT (class_code) DO UPDATE
  SET name = EXCLUDED.name, neta_category = EXCLUDED.neta_category,
      parent_class_id = EXCLUDED.parent_class_id, is_active = EXCLUDED.is_active,
      updated_at = now();

-- Leaves (practical apparatus classes) — neta_category resolved via the parent.
INSERT INTO records.asset_classes (asset_class_id, class_code, name, neta_category, parent_class_id, is_active) VALUES
  ('7783b56c-7f2d-5584-871d-9bf0b2610b07', 'cb_lv', 'LV Circuit Breaker', NULL, 'ed418cb7-bfd9-564d-9bd0-987d7c320b5e', true),
  ('8b105fd5-7065-5b7c-8e58-970bee6341d8', 'cb_mvhv', 'MV/HV Circuit Breaker', NULL, 'ed418cb7-bfd9-564d-9bd0-987d7c320b5e', true),
  ('1527f002-20db-530d-9e6b-ad6b6daacb20', 'xfmr_dry', 'Dry-Type Transformer', NULL, '10d077d6-b28a-5d2f-b192-5225ffe7c946', true),
  ('86ba764e-c167-534c-ac94-434dc831f247', 'xfmr_liquid', 'Liquid-Filled Transformer', NULL, '10d077d6-b28a-5d2f-b192-5225ffe7c946', true),
  ('fdf02c4d-3fa3-538e-afe5-0ab8016e6715', 'swgr_lv_switchboard', 'LV Switchboard', NULL, 'c04a48f5-d000-536f-a2a3-2c38e09bed32', true),
  ('8ae5f3cc-3ae5-59d6-90d7-486c1ce08948', 'swgr_mv_metalclad', 'MV Metal-Clad Switchgear', NULL, 'c04a48f5-d000-536f-a2a3-2c38e09bed32', true),
  ('09368283-295e-5c20-98fa-053dc487e6b9', 'swgr_panelboard', 'Panelboard', NULL, 'c04a48f5-d000-536f-a2a3-2c38e09bed32', true),
  ('7e1512cd-5928-5eb8-acd1-70a1dc9be16f', 'swgr_padmount', 'Pad-Mount Switchgear', NULL, 'c04a48f5-d000-536f-a2a3-2c38e09bed32', true),
  ('4cc24a86-48e0-5d9a-b3f7-c971ed04b75f', 'swgr_vfi', 'VFI Switchgear', NULL, 'c04a48f5-d000-536f-a2a3-2c38e09bed32', true),
  ('e704c23d-002b-564f-90ee-9ab67095fa38', 'it_ct', 'Current Transformer', NULL, 'f42e536f-14bd-5d40-8707-0ad0e7a906e3', true),
  ('f7e4e422-0f4a-5831-af3b-8d94f79a3821', 'it_vt', 'Voltage Transformer', NULL, 'f42e536f-14bd-5d40-8707-0ad0e7a906e3', true),
  ('1cd27d70-9116-56b8-a416-5203628ee826', 'it_cvt', 'Capacitive Voltage Transformer', NULL, 'f42e536f-14bd-5d40-8707-0ad0e7a906e3', true),
  ('e35650c0-47e8-5440-bf7b-45446408b091', 'cable_lv', 'LV Cable', NULL, 'd1d4d633-a0fa-56de-8c56-0022a17d007e', true),
  ('0d09add9-3184-540e-ab99-60a39bb0c084', 'cable_mv', 'MV Cable', NULL, 'd1d4d633-a0fa-56de-8c56-0022a17d007e', true),
  ('8be996fd-2c07-5e78-b3e4-8aad21215fc9', 'busway', 'Busway / Busduct', NULL, 'aaddcd69-3813-506c-ba43-05e700b98dd7', true),
  ('cb36201e-74d6-58b1-9b98-0edf9536a018', 'cap_bank', 'Capacitor Bank', NULL, 'e525bbfa-91f1-527c-9d3e-7e28a2b030a7', true),
  ('9d394bdd-217d-54ec-ad95-cbd1d3db341f', 'reactor', 'Reactor', NULL, 'e525bbfa-91f1-527c-9d3e-7e28a2b030a7', true),
  ('95a845ec-63a4-58c1-a04b-18aa1c104e18', 'ngr', 'Neutral-Grounding Resistor', NULL, 'e525bbfa-91f1-527c-9d3e-7e28a2b030a7', true),
  ('107e7543-30ef-5e21-9a62-483ddcfb64b6', 'harmonic_filter', 'Harmonic Filter Bank', NULL, 'e525bbfa-91f1-527c-9d3e-7e28a2b030a7', true),
  ('c798ab71-0053-5b74-80f5-dc78ef1de9dd', 'mcc_lv', 'LV Motor Control Center', NULL, '19251f8c-0141-54bb-bbee-3f455e997829', true),
  ('54a7cfcd-7129-50d2-b21f-5f17a9767654', 'motor_starter_mv', 'MV Motor Starter', NULL, '19251f8c-0141-54bb-bbee-3f455e997829', true),
  ('896b2de4-1a1e-54bb-b5be-2e4ef0cdf223', 'rm_synchronous', 'Synchronous Machine', NULL, '95250548-46d9-59e5-b698-c3208f562926', true),
  ('70039ba5-ed88-59a8-aee5-9121e1bdc3f4', 'rm_induction', 'Induction Motor', NULL, '95250548-46d9-59e5-b698-c3208f562926', true),
  ('b56ec86b-2dbb-541a-ae50-5d52c931f9cc', 'battery', 'Storage Battery', NULL, '4b655ad2-5102-5e1b-9ce5-6270f4ebac72', true),
  ('0990d692-819c-50b6-95d8-a34a234c0818', 'battery_charger', 'Battery Charger', NULL, '4b655ad2-5102-5e1b-9ce5-6270f4ebac72', true),
  ('bde47fb0-614a-5bf3-b84c-e24535121465', 'ats', 'Automatic Transfer Switch', NULL, 'fc3dbb0d-1469-5794-9699-f128ed4aa9b7', true),
  ('c9a035e3-51d6-5fba-9d41-1e4465b4812e', 'ups', 'Uninterruptible Power Supply', NULL, 'fc3dbb0d-1469-5794-9699-f128ed4aa9b7', true),
  ('d6dc32d9-43fe-5f07-b183-753e59b162be', 'engine_generator', 'Engine Generator', NULL, 'fc3dbb0d-1469-5794-9699-f128ed4aa9b7', true),
  ('e6d4cdc9-1a76-5a33-9edd-c4f85f37fcfe', 'switch_disconnect', 'Disconnect / Load-Interrupter Switch', NULL, 'b86e3489-727b-52cd-970f-932aa3f1dc73', true),
  ('d81054f3-d687-5783-8d74-b50546a60f3d', 'grounding_system', 'Grounding System', NULL, 'c7225c25-d380-5330-850e-81ebc76c5be9', true),
  ('1ca7269e-67c0-597a-ab0a-bdcf09cc4048', 'surge_arrester', 'Surge Arrester', NULL, 'f61bd960-dc83-5348-af99-a4835aaf886d', true),
  ('2b419cd1-2452-57eb-911c-7585336446d2', 'voltage_regulator', 'Voltage Regulator', NULL, '47a6a810-65f0-555f-8396-96c5daecdf3e', true),
  ('e9afca5b-22d3-56ae-94a0-4f8a97771247', 'circuit_switcher', 'Circuit Switcher', NULL, '5c44b02d-5f3d-5db2-83ae-92ddee75de57', true),
  ('47478f9a-0108-5f32-a619-bbd2a22b1377', 'outdoor_bus_structure', 'Outdoor Bus Structure', NULL, 'ff444803-fb28-526d-ad6d-a5605e330ea3', true),
  ('619c64af-51fb-5e81-922e-e91c0aadc97c', 'meter', 'Meter', NULL, '9f3caee7-3185-5030-acbf-38a8f72b5b0f', true),
  ('fb3e710e-885b-53cc-85d0-4a33135e08b7', 'protective_relay', 'Protective Relay', NULL, '279e0012-0285-5bdf-b3e2-6bcab1e06245', true)
ON CONFLICT (class_code) DO UPDATE
  SET name = EXCLUDED.name, neta_category = EXCLUDED.neta_category,
      parent_class_id = EXCLUDED.parent_class_id, is_active = EXCLUDED.is_active,
      updated_at = now();

COMMIT;
