#!/usr/bin/env python3
"""Generate 022_it_pf_readings.sql - complete the IT PF/DF sections with the Doble readings.

Records reconcile slice 2 / D-R1 generalized. The IT templates (015) were built capture-aware, so their
PF/DF sections capture test_kv / pf_pct / watts (+ capacitance on CT/CVT) - but they lack the charging
current (mA) and the temperature-corrected PF a field Doble PF/DF test records and the DTAX TX_PFDF import
carries (the same Doble field set characterized from Prime 56900 in slice 1). Adds current_ma +
pf_corrected_pct to ct.power_factor / vt.power_factor / cvt.capacitance_pf, plus cap_pf to vt.power_factor
(CT/CVT already capture capacitance; VT did not). Additive; idempotent (skips tags already present).

Reads the CURRENT field_schema from records_dev (= 015 capture-aware state) and re-emits the full snapshot
with the new entries, so the capture-mode/import wiring is preserved (no clobber). Mirrors gen_020/021.
Run: uv run --no-project --with "psycopg[binary]" python gen_022_it_pf_readings.py
"""
import json
import os

import psycopg

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "022_it_pf_readings.sql")
PGPW = os.environ.get("RECORDS_DEV_PGPASSWORD") or "TCC_v5_2025"
DSN = os.environ.get("RECORDS_DEV_DSN") or (
    f"host=127.0.0.1 port=5432 dbname=records_dev user=postgres password={PGPW} sslmode=disable"
)

CURRENT_MA = {"tag": "current_ma", "label": "Charging current", "value_kind": "numeric",
              "data_source": "data", "unit": "mA"}
PF_CORR = {"tag": "pf_corrected_pct", "label": "Corrected PF (20degC)", "value_kind": "numeric",
           "data_source": "calc", "unit": "pct"}
CAP_PF = {"tag": "cap_pf", "label": "Capacitance", "value_kind": "numeric",
          "data_source": "data", "unit": "pF"}

# code -> (PF/DF section key, add_cap_pf)
SECTIONS = {"ats_ct_v1": ("power_factor", False),
            "ats_vt_v1": ("power_factor", True),
            "ats_cvt_v1": ("capacitance_pf", False)}


def _insert_after(lst, after_tag, new):
    if any(e.get("tag") == new["tag"] for e in lst):  # idempotent
        return lst
    out, done = [], False
    for e in lst:
        out.append(e)
        if e.get("tag") == after_tag and not done:
            out.append(new)
            done = True
    if not done:
        out.append(new)
    return out


def _patch_list(lst, add_cap):
    lst = _insert_after(list(lst), "test_kv", CURRENT_MA)
    lst = _insert_after(lst, "pf_pct", PF_CORR)
    if add_cap:
        lst = _insert_after(lst, "watts", CAP_PF)
    return lst


def patch(fs, key, add_cap):
    fs = dict(fs)
    out = []
    for s in fs["sections"]:
        if s.get("key") != key:
            out.append(s)
            continue
        s = dict(s)
        if "fields" in s:
            s["fields"] = _patch_list(s["fields"], add_cap)
        else:
            tbl = dict(s["table"])
            tbl["columns"] = _patch_list(tbl["columns"], add_cap)
            s["table"] = tbl
        out.append(s)
    fs["sections"] = out
    return fs


def main():
    lines = [
        "-- =============================================================================",
        "-- Records reconcile slice 2 / D-R1 generalized - complete the IT PF/DF sections.",
        "-- GENERATED by gen_022_it_pf_readings.py - do not edit by hand.",
        "-- Adds current_ma + pf_corrected_pct (calc) to ct.power_factor / vt.power_factor /",
        "-- cvt.capacitance_pf, + cap_pf to vt.power_factor. Read-live snapshot: the 015",
        "-- capture-mode/import wiring is preserved. Idempotent; reversible in _down.",
        "-- =============================================================================",
        "BEGIN;",
        "SET client_encoding TO 'UTF8';",
        "",
    ]
    with psycopg.connect(DSN) as c:
        for code, (key, add_cap) in SECTIONS.items():
            fs = c.execute(
                "select field_schema from records.form_templates where template_code = %s and is_current",
                (code,)
            ).fetchone()[0]
            fs = json.loads(fs) if isinstance(fs, str) else fs
            payload = json.dumps(patch(fs, key, add_cap), ensure_ascii=True,
                                 separators=(",", ":")).replace("'", "''")
            lines += [
                f"UPDATE records.form_templates SET field_schema = '{payload}'::jsonb, updated_at = now()",
                f"  WHERE template_code = '{code}' AND is_current;",
                "",
            ]
    lines.append("COMMIT;")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(SECTIONS)} IT templates patched)")


if __name__ == "__main__":
    main()
