#!/usr/bin/env python3
"""Generate 021_xfmr_pf_readings.sql - add the Doble raw-reading columns to power_factor.

Records reconcile slice 1 / D-R1. Reconciliation against the Prime 56900 TWO-WINDING TRANSFORMER form
(gold-standard Form_Controls.csv) showed our power_factor section holds only pf_pct/capacitance/temp -
too shallow for a field PF test (and for a DTAX/PTM import), which records raw test kV, charging mA and
watts per specimen plus a temperature-corrected PF (Prime tags KV_/mA_/WATTS_/CORR_). This adds
test_kv / current_ma / watts / pf_corrected_pct to the power_factor table on both xfmr templates.
Additive (no NETA-coverage change). Idempotent (skips if already present).

Reads the CURRENT field_schema from records_dev (= 012 base + 020 capture-mode) and re-emits the full
snapshot with the new columns, so the 020 capture wiring is preserved (no clobber). Mirrors gen_020.
Run: uv run --no-project --with "psycopg[binary]" python gen_021_xfmr_pf_readings.py
"""
import json
import os

import psycopg

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "021_xfmr_pf_readings.sql")
PGPW = os.environ.get("RECORDS_DEV_PGPASSWORD") or "TCC_v5_2025"
DSN = os.environ.get("RECORDS_DEV_DSN") or (
    f"host=127.0.0.1 port=5432 dbname=records_dev user=postgres password={PGPW} sslmode=disable"
)
CODES = ["ats_liquid_xfmr_v1", "ats_dry_xfmr_v1"]

# Doble raw readings, inserted around the existing pf_pct column (Prime 56900: KV_/mA_/WATTS_/CORR_).
RAW_BEFORE = [
    {"tag": "test_kv", "label": "Test voltage", "value_kind": "numeric", "data_source": "data", "unit": "kV"},
    {"tag": "current_ma", "label": "Charging current", "value_kind": "numeric", "data_source": "data", "unit": "mA"},
    {"tag": "watts", "label": "Dielectric loss", "value_kind": "numeric", "data_source": "data", "unit": "W"},
]
CORR_AFTER = {"tag": "pf_corrected_pct", "label": "Corrected PF (20degC)", "value_kind": "numeric",
              "data_source": "calc", "unit": "pct"}
NEW_TAGS = {c["tag"] for c in RAW_BEFORE} | {CORR_AFTER["tag"]}


def patch(fs):
    fs = dict(fs)
    out_secs = []
    for s in fs["sections"]:
        if s.get("key") != "power_factor":
            out_secs.append(s)
            continue
        s = dict(s)
        tbl = dict(s["table"])
        cols = tbl["columns"]
        if any(c.get("tag") in NEW_TAGS for c in cols):  # idempotent - already patched
            out_secs.append(s)
            continue
        new_cols = []
        for c in cols:
            if c.get("tag") == "pf_pct":
                new_cols.extend(RAW_BEFORE)
                new_cols.append(c)
                new_cols.append(CORR_AFTER)
            else:
                new_cols.append(c)
        tbl["columns"] = new_cols
        s["table"] = tbl
        out_secs.append(s)
    fs["sections"] = out_secs
    return fs


def main():
    lines = [
        "-- =============================================================================",
        "-- Records reconcile slice 1 / D-R1 - add Doble raw-reading columns to power_factor.",
        "-- GENERATED by gen_021_xfmr_pf_readings.py - do not edit by hand.",
        "-- Adds test_kv / current_ma / watts (raw Doble readings) + pf_corrected_pct (calc)",
        "-- around pf_pct in the power_factor table of both xfmr templates. Read-live snapshot:",
        "-- the 012 base + 020 capture-mode are preserved. Idempotent; reversible in _down.",
        "-- =============================================================================",
        "BEGIN;",
        "SET client_encoding TO 'UTF8';",
        "",
    ]
    with psycopg.connect(DSN) as c:
        for code in CODES:
            fs = c.execute(
                "select field_schema from records.form_templates where template_code = %s and is_current",
                (code,)
            ).fetchone()[0]
            fs = json.loads(fs) if isinstance(fs, str) else fs
            payload = json.dumps(patch(fs), ensure_ascii=True, separators=(",", ":")).replace("'", "''")
            lines += [
                f"UPDATE records.form_templates SET field_schema = '{payload}'::jsonb, updated_at = now()",
                f"  WHERE template_code = '{code}' AND is_current;",
                "",
            ]
    lines.append("COMMIT;")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(CODES)} templates patched)")


if __name__ == "__main__":
    main()
