#!/usr/bin/env python3
"""Generate 020_xfmr_capture_mode.sql - make the transformer templates capture-mode-aware.

Chip 10a (Phase 1). The xfmr datasheets (012) predate the capture-mode contract (015), so they have
capture=NULL and no instrument_import sections. The PTM import needs declared targets: add the
template-level `capture` block + mark the four PTM-fillable sections instrument_import with an
`import {tool: ptm, profile}` hint. Non-PTM sections are untouched; the section set is unchanged
(annotate only). Idempotent (the emitted UPDATE sets the full patched field_schema).

Reads the current field_schema from records_dev, patches in-memory, emits the UPDATE.
Run: uv run --no-project --with "psycopg[binary]" python gen_020_xfmr_capture_mode.py
"""
import json
import os

import psycopg

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "020_xfmr_capture_mode.sql")
PGPW = os.environ.get("RECORDS_DEV_PGPASSWORD") or "TCC_v5_2025"
DSN = os.environ.get("RECORDS_DEV_DSN") or (
    f"host=127.0.0.1 port=5432 dbname=records_dev user=postgres password={PGPW} sslmode=disable"
)
CODES = ["ats_liquid_xfmr_v1", "ats_dry_xfmr_v1"]
CAPTURE = {"modes": ["field", "instrument_import", "cover_attach"], "default": "field"}
# the four PTM-fillable transformer sections -> the import profile naming the bridge
PROFILE = {
    "turns_ratio": "TX_TTR",
    "winding_resistance": "TX_WR",
    "power_factor": "TX_PF",
    "excitation_current": "TX_EXC",
}


def patch(fs):
    fs = dict(fs)
    fs["capture"] = CAPTURE
    out = []
    for s in fs["sections"]:
        s = dict(s)
        if s["key"] in PROFILE:
            s["capture_mode"] = "instrument_import"
            s["import"] = {"tool": "ptm", "profile": PROFILE[s["key"]]}
        out.append(s)
    fs["sections"] = out
    return fs


def main():
    lines = [
        "-- =============================================================================",
        "-- Records Chip 10a (Phase 1) - make the transformer templates capture-mode-aware.",
        "-- GENERATED by gen_020_xfmr_capture_mode.py - do not edit by hand.",
        "-- Adds `capture` + marks turns_ratio / winding_resistance / power_factor /",
        "-- excitation_current `instrument_import` with an `import {tool: ptm, profile}` hint",
        "-- (the PTM import targets). Section set unchanged. Idempotent; reversible in _down.",
        "-- =============================================================================",
        "BEGIN;",
        "SET client_encoding TO 'UTF8';",
        "",
    ]
    with psycopg.connect(DSN) as c:
        for code in CODES:
            fs = c.execute(
                "select field_schema from records.form_templates where template_code = %s and is_current",
                (code,)
            ).fetchone()[0]
            fs = json.loads(fs) if isinstance(fs, str) else fs
            payload = json.dumps(patch(fs), ensure_ascii=True, separators=(",", ":")).replace("'", "''")
            lines += [
                f"UPDATE records.form_templates SET field_schema = '{payload}'::jsonb, updated_at = now()",
                f"  WHERE template_code = '{code}' AND is_current;",
                "",
            ]
    lines.append("COMMIT;")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(CODES)} templates patched)")


if __name__ == "__main__":
    main()
