#!/usr/bin/env python3
"""Generate 039_xfmr_neta_standards_pilot.sql — make ats_liquid_xfmr_v1 standard-aware.

MTS-accommodation Chip B PILOT (one sheet, proves the mechanism before the 33-sheet scale-out).
The ATS sheets declare coverage as a flat `neta_covers` list (ATS item refs). This patch evolves
the liquid-transformer sheet (7.2.2) to the standard-aware v2 shape:

  * field_schema.neta_standards = ["ats","mts"]   (the standards this sheet serves)
  * each section.neta_covers : list  ->  {"ats":[...], "mts":[...]}   (per-standard coverage)
  * each section.standards   : ["ats","mts"]       (the section-level flag; default both —
                              the lever a future whole-section MTS-only block would use)

The MTS coverage is authored from the seeded neta_test_items.mts for 7.2.2 (34 items: 15 VM + 19
electrical) mapped onto the sheet's EXISTING capture sections — no new sections. Acceptance is
unchanged: tolerance_source.table='100.5' now resolves per-standard against the standard-keyed
neta_tables (mig 038). The standard itself is chosen at the submission/test-event (Chip C).

Read-live in-place patch (mirrors gen_020). Run AFTER 012/020/021 are applied (the pre-039 baseline):
  uv run --no-project --with "psycopg[binary]" python gen_039_xfmr_neta_standards.py
"""
import json
import os

import psycopg

import _dbtest

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "039_xfmr_neta_standards_pilot.sql")
OUT_DOWN = os.path.join(HERE, "039_xfmr_neta_standards_pilot_down.sql")
DSN = _dbtest.require_dsn()
CODE = "ats_liquid_xfmr_v1"

# MTS 7.2.2 items (neta_test_items.mts) -> the EXISTING liquid-sheet section that captures them.
# A=visual_mechanical, B=electrical. Covers all 15 VM + 19 electrical = 34 MTS items, each once.
MTS_COVER = {
    "visual_mechanical":      ["7.2.2.A.1", "7.2.2.A.2", "7.2.2.A.3", "7.2.2.A.4", "7.2.2.A.5",
                               "7.2.2.A.6", "7.2.2.A.7", "7.2.2.A.8", "7.2.2.A.9", "7.2.2.A.11",
                               "7.2.2.A.14", "7.2.2.A.15"],
    "gas_blanket":            ["7.2.2.A.10", "7.2.2.B.12"],
    "load_tap_changer":       ["7.2.2.A.12", "7.2.2.B.9"],
    "surge_arresters":        ["7.2.2.A.13", "7.2.2.B.17"],
    "bolted_resistance":      ["7.2.2.B.1"],
    "insulation_resistance":  ["7.2.2.B.2", "7.2.2.B.11"],
    "turns_ratio":            ["7.2.2.B.3"],
    "power_factor":           ["7.2.2.B.4", "7.2.2.B.5"],
    "excitation_current":     ["7.2.2.B.6"],
    "advanced_diagnostics":   ["7.2.2.B.7", "7.2.2.B.10", "7.2.2.B.13"],
    "winding_resistance":     ["7.2.2.B.8"],
    "insulating_liquid":      ["7.2.2.B.14", "7.2.2.B.15"],
    "instrument_transformers": ["7.2.2.B.16"],
    "auxiliary":              ["7.2.2.B.18", "7.2.2.B.19"],
}


def patch(fs):
    fs = dict(fs)
    fs["neta_standards"] = ["ats", "mts"]
    out = []
    for s in fs["sections"]:
        s = dict(s)
        nc = s.get("neta_covers", [])
        ats = nc.get("ats", []) if isinstance(nc, dict) else list(nc)   # idempotent re-patch
        s["neta_covers"] = {"ats": ats, "mts": MTS_COVER.get(s["key"], [])}
        s.setdefault("standards", ["ats", "mts"])
        out.append(s)
    fs["sections"] = out
    return fs


def _update_sql(payload):
    p = json.dumps(payload, ensure_ascii=True, separators=(",", ":")).replace("'", "''")
    return (f"UPDATE records.form_templates SET field_schema = '{p}'::jsonb, updated_at = now()\n"
            f"  WHERE template_code = '{CODE}' AND is_current;")


def main():
    with psycopg.connect(DSN) as c:
        row = c.execute(
            "select field_schema from records.form_templates where template_code = %s and is_current",
            (CODE,)
        ).fetchone()
        assert row, f"{CODE} not found — apply 012/020/021 first"
        s0 = row[0]
        s0 = json.loads(s0) if isinstance(s0, str) else s0
    assert isinstance(s0.get("sections", [{}])[1].get("neta_covers"), list), \
        "baseline neta_covers must be a flat list (apply 012/020/021 first, not a re-patched v2)"
    v2 = patch(s0)

    head = [
        "-- =============================================================================",
        "-- Records MTS-accommodation Chip B PILOT — ats_liquid_xfmr_v1 standard-aware (7.2.2).",
        "-- GENERATED by gen_039_xfmr_neta_standards.py — do not edit by hand.",
        "-- neta_covers list -> {ats,mts} map; +neta_standards; +per-section standards tag.",
        "-- MTS coverage authored from neta_test_items.mts (34 items) onto existing sections.",
        "-- Read-live in-place patch (mirrors 020). Reversible in _down. Requires 012/020/021.",
        "-- =============================================================================",
        "BEGIN;",
        "SET client_encoding TO 'UTF8';",
        "",
        _update_sql(v2),
        "",
        "COMMIT;",
    ]
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(head) + "\n")

    down = [
        "-- =============================================================================",
        "-- DOWN for 039 — restore the pre-039 (flat neta_covers, ATS-only) liquid sheet.",
        "-- =============================================================================",
        "BEGIN;",
        "SET client_encoding TO 'UTF8';",
        "",
        _update_sql(s0),
        "",
        "COMMIT;",
    ]
    with open(OUT_DOWN, "w", encoding="utf-8") as fh:
        fh.write("\n".join(down) + "\n")

    mts_total = sum(len(v) for v in MTS_COVER.values())
    print(f"wrote {OUT}")
    print(f"wrote {OUT_DOWN}")
    print(f"sections={len(v2['sections'])}  mts_refs_mapped={mts_total}")


if __name__ == "__main__":
    main()
