import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'

// The canonical artifact is regenerated by running drawing-nav on Windows (the proprietary PDF is not in
// the repo). This test cannot re-extract; it pins the committed bytes against the manifest so any hand edit
// or differently-produced re-extraction goes red, forcing a conscious manifest update. See the manifest's
// `command` for the exact regen invocation.
const artifactBytes = readFileSync(fileURLToPath(new URL('./fixtures/stack-phx02a-e01-11.artifact.json', import.meta.url)))
const manifest = JSON.parse(
  readFileSync(fileURLToPath(new URL('./fixtures/stack-phx02a-e01-11.artifact.manifest.json', import.meta.url)), 'utf8'),
)

describe('canonical artifact provenance / drift-check', () => {
  it('artifact sha256 matches the manifest (no undocumented byte drift)', () => {
    const sha = createHash('sha256').update(artifactBytes).digest('hex')
    expect(sha).toBe(manifest.sha256)
  })
  it('artifact apparatus count matches the manifest', () => {
    const count = JSON.parse(artifactBytes.toString('utf8')).apparatus.length
    expect(count).toBe(manifest.apparatusCount)
  })
  it('manifest pins the producer commit and the asserted demo tags', () => {
    expect(manifest.producerCommit).toBe('e7a3fb4')
    expect(manifest.voltageAssertionTags).toEqual(['MSB-P1-110-GB', 'ACC-1-09-FB', 'ACC-1-10-FB'])
  })
})
