INSERT INTO tcc._stg_d1_triples(class,triple_id,mfr,type,style) VALUES
('iccb',1,'ABB','PR212','ICCB'),
('iccb',2,'GE','MVT-PM','ICCB'),
('iccb',3,'GE','MVT RMS-9','ICCB'),
('iccb',4,'Merlin Gerin','Masterpact CB','STR 58U'),
('iccb',5,'Siemens','SB-EC','SB'),
('iccb',6,'Square D','Masterpact','STR58U'),
('iccb',7,'Square D','MASTERPACT NW','MICROLOGIC 6.0A'),
('iccb',8,'Square D','Micrologic Full','LE'),
('iccb',9,'Square D','Micrologic Std','LX'),
('iccb',10,'Square D','Micrologic Std','LXI'),
('iccb',11,'Square D','Micrologic Std','MX'),
('iccb',12,'Square D','Micrologic Full','NE'),
('iccb',13,'Square D','Micrologic Std','NX'),
('iccb',14,'Square D','Micrologic Full','PE'),
('iccb',15,'Square D','Micrologic Std','PX-6B'),
('iccb',16,'Square D','Micrologic Full','ICCB SE'),
('iccb',17,'West','Pow-R Trip 7','SPB'),
('iccb',18,'West','SPCB','ICCB'),
('iccb',19,'Cutler-Hammer','Pow-R Trip 7','SPB'),
('iccb',20,'(Generic)','Std','Std'),
('iccb',21,'GE','VersaTrip','THSS'),
('iccb',22,'Cutler-Hammer','Digitrip 1150 i','Magnum Std LSIG'),
('iccb',23,'Cutler-Hammer','Digitrip 1150 i','DoubleWide LSIG'),
('iccb',24,'GE','MVT-Plus','ICCB'),
('iccb',25,'Siemens','ETU 745 L(SIG)','ICCB WL FS I'),
('iccb',26,'Siemens','ETU 745 L(SIG)','ICCB WL FS II-S'),
('iccb',27,'Siemens','ETU 745 L(SIG)','ICCB WL FS II-L'),
('iccb',28,'Siemens','ETU 745 L(SIG)','ICCB WL FS II-C'),
('iccb',29,'Siemens','ETU 745 L(SIG)','ICCBWL FS III-L'),
('iccb',30,'Siemens','ETU 745 L(SIG)','ICCBWL FS III-C'),
('iccb',31,'ABB','PR332/P','ICCB-LSIG'),
('iccb',32,'GE','Entelliguard TU','ICCB'),
('iccb',33,'GE','MVT RMS-9','ICCB (H)'),
('iccb',34,'GE','Ground Break','TGSR'),
('iccb',35,'GE','Integral GF','HPC'),
('iccb',36,'GE','Entelliguard TU','HPC'),
('iccb',37,'GE','VersaTrip MOD2','TPSS'),
('iccb',38,'Cutler-Hammer','DT 520MC Maint','Magnum DS Doubl'),
('iccb',39,'Cutler-Hammer','DT 520MC Maint','Magnum DS Std'),
('iccb',40,'Eaton','DT 520','MSB Double');