INSERT INTO tcc._stg_d1_triples(class,triple_id,mfr,type,style) VALUES
('pcb',1,NULL,NULL,NULL),
('pcb',2,'Cutler-Hammer','OPTIM 750/1050','DS-II'),
('pcb',3,'Cutler-Hammer','OPTIM 750/1050','DSL-II'),
('pcb',4,'GE','Integral GF','HPC'),
('pcb',5,'GE','ME','LVPCB'),
('pcb',6,'Siemens','Static Trip II','LSIG'),
('pcb',7,'Square D','Masterpact','STR58U'),
('pcb',8,'Moeller','IZM32','S'),
('pcb',9,'Merlin Gerin','Statipact 100','DA (DRA)'),
('pcb',10,'(Generic)','Std','Std'),
('pcb',11,'West','DT 510 Series','LVPCB'),
('pcb',12,'Siemens','Static Trip III','LVPCB'),
('pcb',13,'Square D','Ground Censor','GC-100'),
('pcb',14,'GE','Entellisys','LSIG'),
('pcb',15,'Square D','MASTERPACT NW','MICROLOGIC 6.0A'),
('pcb',16,'ABB','PR1/P','LVPCB-LSIG'),
('pcb',17,'Terasaki','AGR-11','AGR-11L'),
('pcb',18,'LS Industrial','OCR-II','LSIG'),
('pcb',19,'LS Industrial','OCR','LSIG'),
('pcb',20,'Siemens','3WN1 [IEC]','AZN'),
('pcb',21,'Hyundai','HAT','AOR-1L-GS'),
('pcb',22,'Cutler-Hammer','DT 520M [IEC]','NF Frame'),
('pcb',23,'Dorman Smith','Z Series','AGR-11B'),
('pcb',24,'Mitsubishi','AE-SWA','LVPCB-WS'),
('pcb',25,'Mitsubishi','AE-SW','LVPCB-WS'),
('pcb',26,'Square D','MASTERPACT NW','MICROLOGIC 5.0A'),
('pcb',27,'WEG','ABW-OCR','OCR Type A'),
('pcb',28,'Merlin Gerin','Masterpact NT','Micrologic 2.0A'),
('pcb',29,'Square D','MicrologicDC1.0','MP NW DC'),
('pcb',30,'Cutler-Hammer','DT 520 Family','Magnum DS Narro'),
('pcb',31,'Cutler-Hammer','DT 520 Family','Magnum DS Std'),
('pcb',32,'Cutler-Hammer','DT 520 Family','Magnum DS Doubl'),
('pcb',33,'Unelec','CNX','RZ1'),
('pcb',34,'OEZ','ETU 45B [IEC]','Arion WL11'),
('pcb',35,'OEZ','ETU 45B [IEC]','Arion WL12'),
('pcb',36,'OEZ','ETU 45B [IEC]','Arion WL13'),
('pcb',37,'GE','M-Pact','M-PRO 40'),
('pcb',38,'GE','M-Pact','M-PRO 27'),
('pcb',39,'West','Pow-R Trip 7','SPB'),
('pcb',40,'GE','Power+','WavePro'),
('pcb',41,'Merlin Gerin','Masterpact CB','STR 58U'),
('pcb',42,'Merlin Gerin','Masterpact CB','STR 18M'),
('pcb',43,'Federal Pacific','HSSA','HSSA1 - LI'),
('pcb',44,'Allis-Chalmers','Static Trip','A-G'),
('pcb',45,'ABB','PR111','LVPCB'),
('pcb',46,'ABB','PR121/P','LVPCB'),
('pcb',47,'GE','RMS-7','LVPCB'),
('pcb',48,'Merlin Gerin','Statipact 100','Selpact (DRS2)'),
('pcb',49,'Eaton','DT 520 [IEC]','NF Frame - LI'),
('pcb',50,'Merlin Gerin','Masterpact NW','Micrologic 6.0'),
('pcb',51,'Siemens','ETU 776 L(SIG)','WL FS II'),
('pcb',52,'Siemens','ETU 745 L(SIG)','WL FS II'),
('pcb',53,'ABB','MPS-C-2000','LSIG'),
('pcb',54,'ABB','Power Shield','SS-5'),
('pcb',55,'ITE','Power Shield','SS-5 (Rev 2)'),
('pcb',56,'People Electric','RDW1','RDW1-1000 H'),
('pcb',57,'Mitsubishi','AE-SS','Type S'),
('pcb',58,'Cutler-Hammer','Digitrip 1150 i','Magnum Std LSIG'),
('pcb',59,'Cutler-Hammer','Digitrip 1150 i','DoubleWide LSIG'),
('pcb',60,'Changshu','CW1','CW1-L'),
('pcb',61,'Changshu','CW2','CW2-L'),
('pcb',62,'Federal Pioneer','USR RMS','LSIG'),
('pcb',63,'Federal Pioneer','SD-6','LVPCB'),
('pcb',64,'Siemens','3WN1 [IEC]','AN'),
('pcb',65,'Fuji','DT3 [IEC]','EN'),
('pcb',66,'Schneider','Easypact','ET2I'),
('pcb',67,'Siemens','ETU 776 L(SIG)','WL FS III'),
('pcb',68,'Siemens','ETU25B [IEC]','3WL11'),
('pcb',69,'Siemens','ETU25B [IEC]','3WL12'),
('pcb',70,'Siemens','ETU25B [IEC]','3WL13'),
('pcb',71,'Siemens','ETU 25B [IEC]','3WL5'),
('pcb',72,'Moeller','IZM32-SV','LVPCB'),
('pcb',73,'Schneider','Compact NS','Micrologic 2.0A'),
('pcb',74,'Schneider','Compact NS','Micrologic 5.0A'),
('pcb',75,'Cutler-Hammer','DT 520M','NF Frame'),
('pcb',76,'Eaton','PXR20/25','NRX-LSI (NF)'),
('pcb',77,'Eaton','PXR20/25','NRX-LSI (RF)'),
('pcb',78,'NHP','MODpower','MTX 3.5'),
('pcb',79,'Square D','MP NW Switch','UL 489'),
('pcb',80,'Square D','MP NW Switch','ANSI C37'),
('pcb',81,'Merlin Gerin','COMPACT NS','MICROLOGIC 5.0E'),
('pcb',82,'Square D','Micrologic 5.0X','MTZ1'),
('pcb',83,'Square D','Micrologic 5.0X','MTZ2'),
('pcb',84,'Square D','Micrologic 5.0X','MTZ3'),
('pcb',85,'Merlin Gerin','Masterpact CB','STR 68 U (IEC)'),
('pcb',86,'Chint','NA','NA1'),
('pcb',87,'Siemens','ETU 776 L(SIG)','WL FS I'),
('pcb',88,'GE','Entel G-GT 50Hz','LVPCB'),
('pcb',89,'Square D','DT 510','LVPCB-LSIG'),
('pcb',90,'Square D','Micrologic 5.0X','MTZ1 [IEC]'),
('pcb',91,'Square D','Micrologic 5.0X','MTZ2 [IEC]'),
('pcb',92,'Square D','Micrologic 5.0X','MTZ3 [IEC]'),
('pcb',93,'Shanghai Electr','bse3','bse3 2000A'),
('pcb',94,'Shanghai Electr','bse3','bse3 3200A'),
('pcb',95,'Shanghai Electr','bse3','bse3 6300A'),
('pcb',96,'Eaton','DT 520','MDS Narrow'),
('pcb',97,'GEIS','ME [IEC]','Mex2'),
('pcb',98,'GE','MVT-PM','LVPCB'),
('pcb',99,'GE','MVT','LVPCB'),
('pcb',100,'GE','MVT-PM (RMS-9D)','LVPCB-LSIG'),
('pcb',101,'GE','MVT-9','LVPCB'),
('pcb',102,'GE','MVT-Plus','LVPCB'),
('pcb',103,'Eaton','Magnum PXR20','Narrow Frm MPN'),
('pcb',104,'Eaton','Magnum PXR20','Std Frm MPS'),
('pcb',105,'ABB','Ekip Touch','LVPCB LSI/G'),
('pcb',106,'ABB','Ekip Dip','LVPCB LSI/G'),
('pcb',107,'Square D','MP NW Switch','IEC 60947-3'),
('pcb',108,'GE','Entelliguard TU','Entel G-Std');