apiVersion: v1
kind: Service
metadata:
  name: forms-engine
  labels:
    app.kubernetes.io/name: forms-engine
    apex.env: host
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: forms-engine
  ports:
    - name: http
      port: 8080
      targetPort: http
